export const LIGTH_TOOGLE = 'LIGTH_TOOGLE';
export const HANDLE_INC = 'HANDLE_INC';
export const GET_COUNT = 'GET_COUNT'; 
export const USERS_GET = 'USERS_GET';
export const USERS_LOADING = 'USERS_LOADIND';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_ERR = 'USERS_ERR';
export const REGISTR_REQUEST = 'REGISTR_REQUEST';
export const REGISTR_SUCCESS = 'REGISTR_SUCCESS';
export const REGISTR_ERROR = 'REGISTR_ERROR';
export const ADDTODO_LOADING = 'ADDTODO_LOADING';
export const ADDTODO_SUCCESS = 'ADDTODO_SUCCESS';
export const ADDTODO_ERROR = 'ADDTODO_ERROR';
export default null;
